spring.application.name=factura

app.inbox.directory=C:\\SimphonyTest\\inbox
app.processed.directory=C:\\SimphonyTest\\Processed
app.webhook.url=https://webhook.site/b02a600b-563a-42f4-954f-b42ea17ac0a6
app.timeout=5000
app.counter.file=factura_counter.txt
app.pendientes.file=facturas_pendientes.json
app.reintento.delay=60000

logging.level.com.prueba.factura.Services.ConeccionWeb=INFO

logging.level.com.prueba.factura.controller.TestController=INFO

logging.level.com.prueba.factura.Services.MiddlewareSimphony=INFO
logging.level.com.prueba.factura.Services.FacturaCounterService=INFO
logging.level.com.prueba.factura.Services.FacturaPendienteService=INFO
logging.level.com.prueba.factura.Services.ReintentarFacturasJob=INFO

resilience4j.ratelimiter.instances.simularPago.registerHealthIndicator=true
resilience4j.ratelimiter.instances.simularPago.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.simularPago.limitForPeriod=5