spring.application.name=factura

app.inbox.directory=C:\\SimphonyTest\\inbox
app.processed.directory=C:\\SimphonyTest\\Processed
app.webhook.url=https://localhost:8080/api/test/mock-webhook
app.timeout=5000
app.counter.file=factura_counter.txt

logging.level.com.prueba.factura.Services.ConeccionWeb=DEBUG
logging.level.com.prueba.factura.Services.ConeccionWeb=WARN
logging.level.com.prueba.factura.Services.ConeccionWeb=ERROR
logging.level.com.prueba.factura.Services.ConeccionWeb=INFO

logging.level.com.prueba.factura.Controller.TestController=DEBUG
logging.level.com.prueba.factura.Controller.TestController=WARN
logging.level.com.prueba.factura.Controller.TestController=ERROR
logging.level.com.prueba.factura.Controller.TestController=INFO

logging.level.com.prueba.factura.Services.MiddlewareSimphony=DEBUG
logging.level.com.prueba.factura.Services.MiddlewareSimphony=WARN
logging.level.com.prueba.factura.Services.MiddlewareSimphony=ERROR
logging.level.com.prueba.factura.Services.MiddlewareSimphony=INFO

resilience4j.ratelimiter.instances.simularPago.registerHealthIndicator=true
resilience4j.ratelimiter.instances.simularPago.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.simularPago.limitForPeriod=20
resilience4j.ratelimiter.instances.simularPago.timeoutDuration=2s