spring.application.name=factura

app.inbox.directory=C:\\SimphonyTest\\inbox
app.processed.directory=C:\\SimphonyTest\\Processed
app.webhook.url=https://localhost:8080/api/test/mock-webhook
app.timeout=5000
app.counter.file=factura_counter.txt
app.pendientes.file=facturas_pendientes.json
app.reintento.delay=60000

logging.level.com.prueba.factura.Services.ConeccionWeb=INFO

logging.level.com.prueba.factura.controller.TestController=INFO

logging.level.com.prueba.factura.Services.MiddlewareSimphony=INFO
logging.level.com.prueba.factura.Services.FacturaCounterService=INFO
logging.level.com.prueba.factura.Services.FacturaPendienteService=INFO
logging.level.com.prueba.factura.Services.ReintentarFacturasJob=INFO
logging.level.com.prueba.factura.Services.DianXmlParserService=INFO
logging.level.com.prueba.factura.controller.DianController=INFO

resilience4j.ratelimiter.instances.simularPago.registerHealthIndicator=true
resilience4j.ratelimiter.instances.simularPago.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.simularPago.limitForPeriod=20
resilience4j.ratelimiter.instances.simularPago.timeoutDuration=2s